USE SCHEMA STREAMLIT_APPS.PUBLIC;

CREATE OR REPLACE TABLE PROJECT_APPROVER_MAP (
    PROJECT_NAME VARCHAR,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

INSERT INTO PROJECT_APPROVER_MAP 
SELECT 'ABC' AS PROJECT_NAME,  TRUE;

CREATE OR REPLACE TABLE TIMESHEETS (
    TIMESHEET_ID NUMBER AUTOINCREMENT,
    EMPLOYEE_EMAIL VARCHAR,
    ENTRY_DATE DATE,
    PROJECT_NAME VARCHAR,
    HOURS_WORKED NUMBER(5,2),
    STATUS VARCHAR,
    SUBMITTED_AT TIMESTAMP_NTZ,
    APPROVED_AT TIMESTAMP_NTZ,
    APPROVED_BY VARCHAR,
    APPROVER_EMAIL VARCHAR,
    REJECTION_REASON VARCHAR
);


select * from TIMESHEETS;



